### ISSUE TITLE
Aggiungere feed rss monitoraggio bandi e avvisi di italiaDomani

### ISSUE THREAD

**Issue by aborruso** [ondata/datiBeneComuneMonitoraggio#16]
Un'idea di @giuragu

**Comment by aborruso** [comment]
https://ondata.github.io/datiBeneComuneMonitoraggio/catalogo/italiaDomaniAvvisiBandi/output/feed.xml

**Comment by giuragu** [comment]
Fantastic! Grazie @aborruso

**Comment by aborruso** [comment]
> Fantastic! Grazie @aborruso

In newsletter poi dettaglio un po' e poi lo scrivo su slack 💋

**Comment by aborruso** [comment]
> Fantastic! Grazie @aborruso

Questo è l'indirizzo feedburner (rimarranno attivi entrambi): http://feeds.feedburner.com/bandi_avvisi_italiadomani_pnrr
