### ISSUE TITLE
Feed RSS documenti italiaDomani: cambiato URL sorgente

### ISSUE THREAD

**Issue by aborruso** [ondata/datiBeneComuneMonitoraggio#17]
Modificare codice

**Comment by giuragu** [comment]
Il feed rimane uguale?


Il sab 25 dic 2021, 11:11 Andrea Borruso ***@***.***> ha
scritto:

**Comment by aborruso** [comment]
> Il feed rimane uguale?

Pure di 25 dicembre?

Sì, rimane uguale

**Comment by giuragu** [comment]
Bene. Auguri allora! :)

Il sab 25 dic 2021, 18:15 Andrea Borruso ***@***.***> ha
scritto:
