### ISSUE TITLE
Attivare archiviazione di base del monitoraggioSettimanale su web archive

### ISSUE THREAD

**Issue by aborruso** [ondata/datiBeneComuneMonitoraggio#3]
Basta dirgli di leggere https://github.com/ondata/datiBeneComuneMonitoraggio/blob/main/catalogo/monitoraggioSettimanale/output/monitoraggioSettimanale.md e seguire i link

**Comment by ClaudiaMazzanti** [comment]
Ciao Andrea,

tra le task ho visto quella della verifica dei report settimanali precedenti a quelli che hai caricato. Ho trovato questo che riguarda la settimana 19 - 25 ottobre.

**Comment by aborruso** [comment]
Ciao @ClaudiaMazzanti e grazie per esserci.

I PDF del monitoraggio settimanale della "settimana 19 - 25 ottobre", li abbiamo già. Soni i file con nome come "Epi_aggiornamento_Lombardia_20201027.pdf", sono insomma quelli associati alla data "2020-10-27" che trovi [qui](https://github.com/ondata/datiBeneComuneMonitoraggio/blob/main/catalogo/monitoraggioSettimanale/output/monitoraggioSettimanale.md).

![image](https://user-images.githubusercontent.com/30607/100330760-a4875380-2fcf-11eb-88d1-4eff05473372.png)

Il riferimento a file più "vecchi" è per i cosiddetti "Indicatori per la valutazione del rischio", che di base si trovano [qui](http://www.salute.gov.it/portale/nuovocoronavirus/dettaglioContenutiNuovoCoronavirus.jsp?lingua=italiano&id=5351&area=nuovoCoronavirus&menu=vuoto), in corrispondenza dei monitoraggi regionali.

I monitoraggi regionali ci sono da mesi, quindi siamo al 27simo, probabilmente i report con gli indicatori (come [questo](http://www.salute.gov.it/imgs/C_17_notizie_5182_0_file.pdf)), ci sono soltanto dal DPCM in qui sono stati introdotti il giallo, l'arancione e il rosso.

Cla, non ne sonco certo, quindi fammi le pulci :)

**Comment by ClaudiaMazzanti** [comment]
Grazie della specifica. Scusa ma avevo visto in una tabella dei link al sito del ministero con i file di monitoraggio settimanali a partire dal 26 ottobre e mi pareva mancassero quelli precedenti che sicuramente avevano anche una visualizzazione diversa.  Così da una velocissima ricerca online avevo trovato questo...
Sicuramente tu hai il polso della situazione più di me!
